version: '3.8'

services:
  trading-bot:
    build: .
    env_file:
      - .env  # Now using .env instead of config.env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
