version: '3.8'

services:
  trading-bot:
    build: .
    env_file:
      - config.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
